general:
  verbose: true
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    verbose: true
    deployTool: 'cf_native'
    deployType: 'standard'
    cloudFoundry:
      org: 'D046169trial_trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'