steps:
  mtaBuild:
    buildTarget: 'CF'
cloudFoundryDeploy:
    deployTool: 'cf_native'
    deployType: 'standard'
    cloudFoundry:
      org: 'D046169trial_trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'