general:
  verbose: true
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    verbose: true
    deployTool: 'mtaDeployPlugin'
    deployType: 'blue-green'
    cloudFoundry:
      org: 'D046169trial_trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'